build:
    verbosity: detailed

image: Visual Studio 2017

install:
  - ps: Install-Product node 8 x64

build_script:
    - cmd: yarn
    - cmd: dotnet restore
    - cmd: cd src/docs
    - cmd: dotnet fable yarn-build

cache:
  - "%LOCALAPPDATA%\\Yarn"